server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 1337
    url: jdbc:postgresql://localhost:5432/cscc43
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  shell:
    interactive:
      enabled: true
    script:
      enabled: true